version: "3.8"
services:
  ios_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: jkf&.i3+eTDkds49
      POSTGRES_DB: ios_prod
    ports:
      - "5432:5432"
    volumes:
      - postgres-data-prod:/var/lib/postgresql/data

  server:
    build:
      context: ./server
    ports:
      - "3333:3333"
    depends_on:
      - ios_db

  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  postgres-data-prod:
